language: go

go:
  - "1.12"

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
# env:
#   - GO111MODULE=on
#   - GOFLAGS='-mod vendor'

install:
  - go get -u golang.org/x/lint/golint

script:
  - GO111MODULE=on GOFLAGS='-mod vendor' make test

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true